import type { Vendor } from '@/types/catalog';

export const vendors: Vendor[] = [
  {
    id: 'vnd_apex',
    name: 'Apex Office Solutions',
    slug: 'apex-office-solutions',
    logo: 'https://api.dicebear.com/9.x/initials/svg?seed=Apex%20Office&backgroundType=gradientLinear',
    banner:
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
    rating: 4.8,
    reviewCount: 2140,
    verified: true,
    location: 'Austin, TX',
    responseTime: '< 2 hours',
    yearsActive: 9,
    fulfillmentRate: 98.6,
    certifications: ['ISO 9001', 'GSA Approved'],
    categories: ['cat_furniture', 'cat_office'],
    status: 'approved',
    contactPerson: 'Rebecca Hall',
    email: 'partners@apexoffice.com',
    phone: '(512) 555-0110',
    address: '2200 Commerce Park Dr, Austin, TX 78701',
    registeredAt: '2017-03-14',
    performanceScore: 94,
  },
  {
    id: 'vnd_freshstock',
    name: 'FreshStock Wholesale',
    slug: 'freshstock-wholesale',
    logo: 'https://api.dicebear.com/9.x/initials/svg?seed=FreshStock&backgroundType=gradientLinear',
    banner:
      'https://images.unsplash.com/photo-1578916171728-46686eac8d58?q=80&w=1200&auto=format&fit=crop',
    rating: 4.6,
    reviewCount: 1580,
    verified: true,
    location: 'Chicago, IL',
    responseTime: '< 1 hour',
    yearsActive: 6,
    fulfillmentRate: 97.2,
    certifications: ['HACCP', 'FDA Registered'],
    categories: ['cat_grocery'],
    status: 'approved',
    contactPerson: 'Daniel Osei',
    email: 'sales@freshstockwholesale.com',
    phone: '(312) 555-0182',
    address: '880 Lakefront Ave, Chicago, IL 60601',
    registeredAt: '2020-06-02',
    performanceScore: 89,
  },
  {
    id: 'vnd_technova',
    name: 'TechNova Distribution',
    slug: 'technova-distribution',
    logo: 'https://api.dicebear.com/9.x/initials/svg?seed=TechNova&backgroundType=gradientLinear',
    banner:
      'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
    rating: 4.9,
    reviewCount: 3260,
    verified: true,
    location: 'San Jose, CA',
    responseTime: '< 3 hours',
    yearsActive: 12,
    fulfillmentRate: 99.1,
    certifications: ['ISO 27001', 'Authorized Reseller'],
    categories: ['cat_it', 'cat_electrical'],
    status: 'approved',
    contactPerson: 'Priya Nair',
    email: 'partnerships@technova.com',
    phone: '(408) 555-0199',
    address: '1 Innovation Way, San Jose, CA 95110',
    registeredAt: '2014-01-20',
    performanceScore: 97,
  },
  {
    id: 'vnd_clearline',
    name: 'ClearLine Janitorial Supply',
    slug: 'clearline-janitorial-supply',
    logo: 'https://api.dicebear.com/9.x/initials/svg?seed=ClearLine&backgroundType=gradientLinear',
    banner:
      'https://images.unsplash.com/photo-1563453392212-326f5e854473?q=80&w=1200&auto=format&fit=crop',
    rating: 4.5,
    reviewCount: 940,
    verified: true,
    location: 'Denver, CO',
    responseTime: '< 4 hours',
    yearsActive: 5,
    fulfillmentRate: 96.4,
    certifications: ['Green Seal Certified'],
    categories: ['cat_cleaning'],
    status: 'approved',
    contactPerson: 'Sofia Reyes',
    email: 'accounts@clearlinesupply.com',
    phone: '(720) 555-0143',
    address: '410 Industrial Blvd, Denver, CO 80216',
    registeredAt: '2021-09-11',
    performanceScore: 85,
  },
  {
    id: 'vnd_voltedge',
    name: 'VoltEdge Electrical',
    slug: 'voltedge-electrical',
    logo: 'https://api.dicebear.com/9.x/initials/svg?seed=VoltEdge&backgroundType=gradientLinear',
    banner:
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=1200&auto=format&fit=crop',
    rating: 4.7,
    reviewCount: 1120,
    verified: true,
    location: 'Charlotte, NC',
    responseTime: '< 2 hours',
    yearsActive: 8,
    fulfillmentRate: 97.8,
    certifications: ['UL Listed', 'NECA Member'],
    categories: ['cat_electrical'],
    status: 'approved',
    contactPerson: 'Marcus Boyd',
    email: 'vendor@voltedge.com',
    phone: '(704) 555-0167',
    address: '75 Powerline Rd, Charlotte, NC 28206',
    registeredAt: '2018-11-05',
    performanceScore: 91,
  },
  {
    id: 'vnd_nextgen',
    name: 'NextGen IT Partners',
    slug: 'nextgen-it-partners',
    logo: 'https://api.dicebear.com/9.x/initials/svg?seed=NextGen&backgroundType=gradientLinear',
    banner:
      'https://images.unsplash.com/photo-1487014679447-9f8336841d58?q=80&w=1200&auto=format&fit=crop',
    rating: 4.2,
    reviewCount: 210,
    verified: false,
    location: 'Dallas, TX',
    responseTime: '< 6 hours',
    yearsActive: 2,
    fulfillmentRate: 91.4,
    certifications: [],
    categories: ['cat_it'],
    status: 'pending',
    contactPerson: 'Aisha Rahman',
    email: 'onboarding@nextgenit.com',
    phone: '(214) 555-0129',
    address: '900 Commerce St, Dallas, TX 75201',
    registeredAt: '2026-08-01',
    performanceScore: 68,
  },
  {
    id: 'vnd_budgetsupply',
    name: 'BudgetSupply Direct',
    slug: 'budgetsupply-direct',
    logo: 'https://api.dicebear.com/9.x/initials/svg?seed=Budget%20Supply&backgroundType=gradientLinear',
    banner:
      'https://images.unsplash.com/photo-1553413077-190083ec01b6?q=80&w=1200&auto=format&fit=crop',
    rating: 3.4,
    reviewCount: 58,
    verified: false,
    location: 'Reno, NV',
    responseTime: '> 24 hours',
    yearsActive: 1,
    fulfillmentRate: 78.2,
    certifications: [],
    categories: ['cat_office'],
    status: 'rejected',
    contactPerson: 'Carlos Mendes',
    email: 'hello@budgetsupplydirect.com',
    phone: '(775) 555-0111',
    address: '210 Sparks Ave, Reno, NV 89501',
    registeredAt: '2026-07-22',
    performanceScore: 42,
  },
];

export function getVendorsByCategory(categoryId: string): Vendor[] {
  return vendors.filter(
    (vendor) => vendor.categories.includes(categoryId) && vendor.status === 'approved',
  );
}
