import type {
  AppNotification,
  ChatMessage,
  ChatThread,
  Client,
  InvoiceAlertLogEntry,
  InvoiceAlertRule,
  Quotation,
  VendorPurchase,
} from '@/types/admin';

/**
 * client_1 (Cascade Financial Group) is the account associated with the demo
 * customer login (user@example.com) so the customer portal has realistic,
 * pre-populated credit / invoice / quotation / chat data to demo against.
 */
export const clients: Client[] = [
  {
    id: 'client_1',
    companyName: 'Cascade Financial Group',
    contactName: 'Jordan Ellis',
    email: 'user@example.com',
    phone: '(512) 555-0134',
    address: '4400 Riverside Plaza, Austin, TX 78701',
    status: 'active',
    creditLimit: 25000,
    creditUsed: 11060,
    creditFrozen: false,
    outstandingBalance: 13210,
    dueAmount: 4820,
    nextDueDate: '2026-08-19',
    joinedAt: '2023-02-10',
    orderCount: 48,
    totalSpend: 182400,
    taxId: 'US-84-2210934',
    billingEmail: 'billing@cascadefinancial.com',
    addresses: [
      {
        id: 'addr_1',
        label: 'Headquarters',
        line1: '4400 Riverside Plaza',
        line2: 'Suite 200',
        city: 'Austin',
        state: 'TX',
        postalCode: '78701',
        country: 'United States',
        isDefault: true,
      },
      {
        id: 'addr_2',
        label: 'Warehouse Annex',
        line1: '118 Freight Yard Rd',
        city: 'Round Rock',
        state: 'TX',
        postalCode: '78664',
        country: 'United States',
        isDefault: false,
      },
    ],
  },
  {
    id: 'client_2',
    companyName: 'Meridian Health Systems',
    contactName: 'Dr. Alina Foster',
    email: 'accounts@meridianhealth.com',
    phone: '(720) 555-0166',
    address: '900 Wellness Pkwy, Denver, CO 80206',
    status: 'active',
    creditLimit: 50000,
    creditUsed: 12400,
    creditFrozen: false,
    outstandingBalance: 0,
    dueAmount: 0,
    nextDueDate: null,
    joinedAt: '2021-11-01',
    orderCount: 112,
    totalSpend: 640200,
    addresses: [
      {
        id: 'addr_3',
        label: 'Main Campus',
        line1: '900 Wellness Pkwy',
        city: 'Denver',
        state: 'CO',
        postalCode: '80206',
        country: 'United States',
        isDefault: true,
      },
    ],
  },
  {
    id: 'client_3',
    companyName: 'Brightline Logistics',
    contactName: 'Marcus Boyd',
    email: 'ap@brightlinelogistics.com',
    phone: '(704) 555-0122',
    address: '75 Depot St, Charlotte, NC 28206',
    status: 'active',
    creditLimit: 15000,
    creditUsed: 3260,
    creditFrozen: false,
    outstandingBalance: 2060,
    dueAmount: 2060,
    nextDueDate: '2026-07-28',
    joinedAt: '2024-05-19',
    orderCount: 26,
    totalSpend: 94500,
    addresses: [],
  },
  {
    id: 'client_4',
    companyName: 'Horizon Manufacturing',
    contactName: 'Sara Kim',
    email: 'finance@horizonmfg.com',
    phone: '(414) 555-0155',
    address: '210 Fabrication Way, Milwaukee, WI 53202',
    status: 'suspended',
    creditLimit: 20000,
    creditUsed: 8890,
    creditFrozen: true,
    outstandingBalance: 8890,
    dueAmount: 8890,
    nextDueDate: '2026-07-10',
    joinedAt: '2022-08-23',
    orderCount: 33,
    totalSpend: 211300,
    addresses: [],
  },
  {
    id: 'client_5',
    companyName: 'Northgate Retail Group',
    contactName: 'Priya Nair',
    email: 'procurement@northgateretail.com',
    phone: '(312) 555-0188',
    address: '55 Commerce Loop, Chicago, IL 60607',
    status: 'active',
    creditLimit: 10000,
    creditUsed: 0,
    creditFrozen: false,
    outstandingBalance: 0,
    dueAmount: 0,
    nextDueDate: null,
    joinedAt: '2026-06-14',
    orderCount: 3,
    totalSpend: 8600,
    addresses: [],
  },
];

export function getClientById(id: string): Client | undefined {
  return clients.find((client) => client.id === id);
}

export function getClientByEmail(email: string): Client | undefined {
  return clients.find((client) => client.email.toLowerCase() === email.toLowerCase());
}

export const quotations: Quotation[] = [
  {
    id: 'quo_1',
    quotationNumber: 'QT-1042',
    clientId: 'client_1',
    productName: 'ApexErgoFlex Mesh Office Chair',
    quantity: 120,
    unit: 'unit',
    notes: 'Need matching finish across regional offices.',
    estimatedTotal: 29800,
    status: 'approved',
    requestedAt: '2026-07-28T10:15:00Z',
    respondedAt: '2026-07-30T14:00:00Z',
    vendorName: 'Apex Office Solutions',
  },
  {
    id: 'quo_2',
    quotationNumber: 'QT-1058',
    clientId: 'client_1',
    productName: 'TechNova ProBook 14" Laptop',
    quantity: 45,
    unit: 'unit',
    estimatedTotal: 49500,
    status: 'requested',
    requestedAt: '2026-08-05T09:30:00Z',
    respondedAt: null,
    vendorName: 'TechNova Distribution',
  },
  {
    id: 'quo_3',
    quotationNumber: 'QT-0994',
    clientId: 'client_1',
    productName: 'ClearLine Industrial Disinfectant',
    quantity: 200,
    unit: 'case',
    estimatedTotal: 15600,
    status: 'rejected',
    requestedAt: '2026-06-30T11:00:00Z',
    respondedAt: '2026-07-02T16:20:00Z',
    vendorName: 'ClearLine Janitorial Supply',
  },
  {
    id: 'quo_4',
    quotationNumber: 'QT-1071',
    clientId: 'client_2',
    productName: 'VoltEdge LED Panel Light',
    quantity: 300,
    unit: 'unit',
    estimatedTotal: 22800,
    status: 'requested',
    requestedAt: '2026-08-08T13:45:00Z',
    respondedAt: null,
    vendorName: 'VoltEdge Electrical',
  },
];

export function getQuotationsByClient(clientId: string): Quotation[] {
  return quotations.filter((quotation) => quotation.clientId === clientId);
}

export const chatThreads: ChatThread[] = [
  {
    id: 'thread_1',
    clientId: 'client_1',
    clientName: 'Cascade Financial Group',
    subject: 'Invoice INV-30021 payment plan',
    relatedInvoiceNumber: 'INV-30021',
    lastMessagePreview: "We'd like to split this into two payments if possible.",
    lastMessageAt: '2026-08-10T15:22:00Z',
    unreadForAdmin: 1,
    unreadForCustomer: 0,
  },
  {
    id: 'thread_2',
    clientId: 'client_3',
    clientName: 'Brightline Logistics',
    subject: 'Order GO-2026-07602 missing items',
    relatedOrderNumber: 'GO-2026-07602',
    lastMessagePreview: 'Sending photos of the delivered pallet now.',
    lastMessageAt: '2026-08-09T14:20:00Z',
    unreadForAdmin: 2,
    unreadForCustomer: 0,
  },
  {
    id: 'thread_3',
    clientId: 'client_4',
    clientName: 'Horizon Manufacturing',
    subject: 'Credit account frozen - request review',
    lastMessagePreview: 'Can we schedule a call to discuss the overdue balance?',
    lastMessageAt: '2026-08-07T09:10:00Z',
    unreadForAdmin: 0,
    unreadForCustomer: 1,
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'msg_1',
    threadId: 'thread_1',
    senderRole: 'customer',
    senderName: 'Jordan Ellis',
    body: "Hi team, we received invoice INV-30021 for $4,820. We'd like to split this into two payments if possible.",
    createdAt: '2026-08-10T15:22:00Z',
    readAt: '2026-08-10T15:30:00Z',
  },
  {
    id: 'msg_2',
    threadId: 'thread_1',
    senderRole: 'admin',
    senderName: 'GoOrder Admin',
    body: 'Thanks for reaching out, Jordan. Let me check with our finance team and get back to you today.',
    createdAt: '2026-08-10T15:34:00Z',
    readAt: '2026-08-10T15:40:00Z',
  },
  {
    id: 'msg_3',
    threadId: 'thread_2',
    senderRole: 'customer',
    senderName: 'Marcus Boyd',
    body: 'Order GO-2026-07602 arrived short by 4 cartons. Sending photos of the delivered pallet now.',
    attachments: [
      { id: 'att_1', name: 'pallet-photo-1.jpg', type: 'image', url: '#', size: '1.2 MB' },
      { id: 'att_2', name: 'delivery-note.pdf', type: 'pdf', url: '#', size: '340 KB' },
    ],
    createdAt: '2026-08-09T14:20:00Z',
    readAt: null,
  },
  {
    id: 'msg_4',
    threadId: 'thread_3',
    senderRole: 'admin',
    senderName: 'GoOrder Admin',
    body: 'Your credit account was frozen due to the overdue balance on INV-29988. Can we schedule a call to discuss?',
    createdAt: '2026-08-07T09:10:00Z',
    readAt: null,
  },
];

export function getThreadsForClient(clientId: string): ChatThread[] {
  return chatThreads.filter((thread) => thread.clientId === clientId);
}

export function getMessagesForThread(threadId: string): ChatMessage[] {
  return chatMessages
    .filter((message) => message.threadId === threadId)
    .sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
}

export const vendorPurchases: VendorPurchase[] = [
  {
    id: 'vp_1',
    vendorId: 'vnd_technova',
    vendorName: 'TechNova Distribution',
    productName: 'TechNova ProBook 14" Laptop',
    quantity: 150,
    purchaseCost: 138750,
    purchaseDate: '2026-07-28',
    expectedDeliveryDate: '2026-08-04',
    deliveryDate: '2026-08-05',
    deliveryStatus: 'received',
    invoiceStatus: 'paid',
  },
  {
    id: 'vp_2',
    vendorId: 'vnd_apex',
    vendorName: 'Apex Office Solutions',
    productName: 'ApexErgoFlex Mesh Office Chair',
    quantity: 200,
    purchaseCost: 42000,
    purchaseDate: '2026-08-01',
    expectedDeliveryDate: '2026-08-11',
    deliveryDate: '2026-08-12',
    deliveryStatus: 'received',
    invoiceStatus: 'billed',
  },
  {
    id: 'vp_3',
    vendorId: 'vnd_freshstock',
    vendorName: 'FreshStock Wholesale',
    productName: 'FreshStock Premium Arabica Coffee',
    quantity: 500,
    purchaseCost: 12500,
    purchaseDate: '2026-08-04',
    expectedDeliveryDate: '2026-08-14',
    deliveryDate: null,
    deliveryStatus: 'shipped',
    invoiceStatus: 'unbilled',
  },
  {
    id: 'vp_4',
    vendorId: 'vnd_clearline',
    vendorName: 'ClearLine Janitorial Supply',
    productName: 'ClearLine Industrial Disinfectant',
    quantity: 150,
    purchaseCost: 9750,
    purchaseDate: '2026-07-20',
    expectedDeliveryDate: '2026-07-29',
    deliveryDate: '2026-07-30',
    deliveryStatus: 'received',
    invoiceStatus: 'paid',
  },
  {
    id: 'vp_5',
    vendorId: 'vnd_voltedge',
    vendorName: 'VoltEdge Electrical',
    productName: 'VoltEdge LED Panel Light',
    quantity: 300,
    purchaseCost: 24900,
    purchaseDate: '2026-08-06',
    expectedDeliveryDate: '2026-08-16',
    deliveryDate: null,
    deliveryStatus: 'ordered',
    invoiceStatus: 'unbilled',
  },
];

export const invoiceAlertRules: InvoiceAlertRule[] = [
  {
    id: 'alert_7day',
    timing: '7-day',
    label: '7 days before due date',
    description: 'Gentle reminder sent a week before the invoice is due.',
    channels: ['dashboard', 'email'],
    recipients: ['client'],
    enabled: true,
  },
  {
    id: 'alert_3day',
    timing: '3-day',
    label: '3 days before due date',
    description: 'Follow-up reminder as the due date approaches.',
    channels: ['dashboard', 'email'],
    recipients: ['client'],
    enabled: true,
  },
  {
    id: 'alert_due_today',
    timing: 'due-today',
    label: 'Due today',
    description: 'Final notice sent on the day payment is due.',
    channels: ['dashboard', 'email', 'sms'],
    recipients: ['client', 'admin'],
    enabled: true,
  },
  {
    id: 'alert_overdue',
    timing: 'overdue',
    label: 'Overdue',
    description: 'Escalating reminders once an invoice passes its due date.',
    channels: ['dashboard', 'email', 'sms'],
    recipients: ['client', 'admin'],
    enabled: true,
  },
];

export const invoiceAlertLog: InvoiceAlertLogEntry[] = [
  {
    id: 'log_1',
    invoiceNumber: 'INV-30021',
    clientName: 'Cascade Financial Group',
    timing: '7-day',
    channel: 'email',
    recipient: 'client',
    sentAt: '2026-08-12T08:00:00Z',
  },
  {
    id: 'log_2',
    invoiceNumber: 'INV-29988',
    clientName: 'Horizon Manufacturing',
    timing: 'overdue',
    channel: 'sms',
    recipient: 'client',
    sentAt: '2026-08-11T08:00:00Z',
  },
  {
    id: 'log_3',
    invoiceNumber: 'INV-29988',
    clientName: 'Horizon Manufacturing',
    timing: 'overdue',
    channel: 'dashboard',
    recipient: 'admin',
    sentAt: '2026-08-11T08:00:00Z',
  },
  {
    id: 'log_4',
    invoiceNumber: 'INV-30032',
    clientName: 'Brightline Logistics',
    timing: '3-day',
    channel: 'email',
    recipient: 'client',
    sentAt: '2026-07-25T08:00:00Z',
  },
];

export const notifications: AppNotification[] = [
  {
    id: 'note_1',
    type: 'invoice',
    title: 'Invoice INV-30021 due in 7 days',
    message: '$4,820 due on Aug 19, 2026.',
    createdAt: '2026-08-12T08:00:00Z',
    read: false,
    href: '/invoices',
  },
  {
    id: 'note_2',
    type: 'credit',
    title: 'Credit utilization at 44%',
    message: 'You have $13,940 of available credit remaining.',
    createdAt: '2026-08-11T09:00:00Z',
    read: false,
    href: '/credit',
  },
  {
    id: 'note_3',
    type: 'delivery',
    title: 'Order GO-2026-07988 is out for delivery',
    message: 'Expected today between 4-6 PM.',
    createdAt: '2026-08-10T13:00:00Z',
    read: true,
    href: '/orders/GO-2026-07988',
  },
  {
    id: 'note_4',
    type: 'payment',
    title: 'Payment received for INV-30014',
    message: '$12,400 payment confirmed.',
    createdAt: '2026-08-04T10:00:00Z',
    read: true,
    href: '/invoices',
  },
  {
    id: 'note_5',
    type: 'invoice',
    title: 'Quotation QT-1058 awaiting vendor response',
    message: 'TechNova Distribution is preparing your quote.',
    createdAt: '2026-08-05T09:35:00Z',
    read: true,
    href: '/quotations',
  },
];
