import type {
  Asset,
  Bid,
  DeliveryJob,
  DemandForecastItem,
  Invoice,
  InventoryItem,
  LedgerEntry,
  RfqRequest,
  SupportTicket,
  Tender,
  WarehouseStock,
} from '@/types/enterprise';

export const invoices: Invoice[] = [
  {
    id: 'inv_1',
    invoiceNumber: 'INV-30021',
    vendorOrCustomer: 'Cascade Financial Group',
    clientId: 'client_1',
    type: 'receivable',
    issueDate: '2026-07-20',
    dueDate: '2026-08-19',
    amount: 4820,
    amountPaid: 0,
    status: 'sent',
    orderNumber: 'GO-2026-07988',
  },
  {
    id: 'inv_2',
    invoiceNumber: 'INV-30014',
    vendorOrCustomer: 'Meridian Health Systems',
    clientId: 'client_2',
    type: 'receivable',
    issueDate: '2026-07-05',
    dueDate: '2026-08-04',
    amount: 12400,
    amountPaid: 12400,
    status: 'paid',
    orderNumber: 'GO-2026-07711',
  },
  {
    id: 'inv_3',
    invoiceNumber: 'INV-30032',
    vendorOrCustomer: 'Brightline Logistics',
    clientId: 'client_3',
    type: 'receivable',
    issueDate: '2026-06-28',
    dueDate: '2026-07-28',
    amount: 3260,
    amountPaid: 1200,
    status: 'partial',
    orderNumber: 'GO-2026-07602',
  },
  {
    id: 'inv_4',
    invoiceNumber: 'INV-29988',
    vendorOrCustomer: 'Horizon Manufacturing',
    clientId: 'client_4',
    type: 'receivable',
    issueDate: '2026-06-10',
    dueDate: '2026-07-10',
    amount: 8890,
    amountPaid: 0,
    status: 'overdue',
    orderNumber: 'GO-2026-07220',
  },
  {
    id: 'inv_5',
    invoiceNumber: 'BILL-8821',
    vendorOrCustomer: 'Apex Office Solutions',
    type: 'payable',
    issueDate: '2026-07-15',
    dueDate: '2026-08-14',
    amount: 15200,
    amountPaid: 0,
    status: 'sent',
  },
  {
    id: 'inv_6',
    invoiceNumber: 'BILL-8790',
    vendorOrCustomer: 'TechNova Distribution',
    type: 'payable',
    issueDate: '2026-07-02',
    dueDate: '2026-08-01',
    amount: 42500,
    amountPaid: 42500,
    status: 'paid',
  },
  {
    id: 'inv_7',
    invoiceNumber: 'CR-1042',
    vendorOrCustomer: 'Cascade Financial Group',
    clientId: 'client_1',
    type: 'receivable',
    issueDate: '2026-08-01',
    dueDate: '2026-08-31',
    amount: 6240,
    amountPaid: 0,
    status: 'credit',
    orderNumber: 'GO-2026-08421',
  },
  {
    id: 'inv_8',
    invoiceNumber: 'INV-30045',
    vendorOrCustomer: 'Cascade Financial Group',
    clientId: 'client_1',
    type: 'receivable',
    issueDate: '2026-08-10',
    dueDate: '2026-08-13',
    amount: 2150,
    amountPaid: 0,
    status: 'draft',
    orderNumber: 'GO-2026-08502',
  },
];

export const ledgerEntries: LedgerEntry[] = [
  {
    id: 'gl_1',
    date: '2026-08-05',
    account: 'Accounts Receivable',
    description: 'Invoice INV-30021 issued',
    debit: 4820,
    credit: 0,
  },
  {
    id: 'gl_2',
    date: '2026-08-05',
    account: 'Sales Revenue',
    description: 'Order GO-2026-07988 recognized',
    debit: 0,
    credit: 4820,
  },
  {
    id: 'gl_3',
    date: '2026-08-04',
    account: 'Cash',
    description: 'Payment received INV-30014',
    debit: 12400,
    credit: 0,
  },
  {
    id: 'gl_4',
    date: '2026-08-04',
    account: 'Accounts Receivable',
    description: 'Invoice INV-30014 settled',
    debit: 0,
    credit: 12400,
  },
  {
    id: 'gl_5',
    date: '2026-08-01',
    account: 'Inventory',
    description: 'Stock received from TechNova',
    debit: 42500,
    credit: 0,
  },
  {
    id: 'gl_6',
    date: '2026-08-01',
    account: 'Accounts Payable',
    description: 'Bill BILL-8790 recorded',
    debit: 0,
    credit: 42500,
  },
  {
    id: 'gl_7',
    date: '2026-07-30',
    account: 'Operating Expense',
    description: 'Warehouse lease - August',
    debit: 9800,
    credit: 0,
  },
  {
    id: 'gl_8',
    date: '2026-07-30',
    account: 'Cash',
    description: 'Warehouse lease payment',
    debit: 0,
    credit: 9800,
  },
];

export const warehouses: WarehouseStock[] = [
  {
    id: 'wh_1',
    warehouseName: 'Austin Distribution Center',
    location: 'Austin, TX',
    utilization: 78,
    capacityUnits: 40000,
    usedUnits: 31200,
  },
  {
    id: 'wh_2',
    warehouseName: 'Chicago Regional Hub',
    location: 'Chicago, IL',
    utilization: 62,
    capacityUnits: 32000,
    usedUnits: 19840,
  },
  {
    id: 'wh_3',
    warehouseName: 'Denver Fulfillment Center',
    location: 'Denver, CO',
    utilization: 91,
    capacityUnits: 18000,
    usedUnits: 16380,
  },
  {
    id: 'wh_4',
    warehouseName: 'Charlotte East Hub',
    location: 'Charlotte, NC',
    utilization: 45,
    capacityUnits: 22000,
    usedUnits: 9900,
  },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: 'invn_1',
    sku: 'APX-PPR-0456',
    name: 'Apex Premium Copy Paper (Case)',
    warehouse: 'Austin Distribution Center',
    onHand: 82,
    reserved: 30,
    reorderPoint: 100,
    reorderQty: 400,
    status: 'critical',
    category: 'Office Supplies',
    unitCost: 28,
  },
  {
    id: 'invn_2',
    sku: 'APX-CHR-1029',
    name: 'ApexErgoFlex Mesh Office Chair',
    warehouse: 'Austin Distribution Center',
    onHand: 340,
    reserved: 40,
    reorderPoint: 150,
    reorderQty: 200,
    status: 'healthy',
    category: 'Office Furniture',
    unitCost: 145,
  },
  {
    id: 'invn_3',
    sku: 'TNV-LAP-5521',
    name: 'TechNova ProBook 14" Laptop',
    warehouse: 'Chicago Regional Hub',
    onHand: 55,
    reserved: 38,
    reorderPoint: 60,
    reorderQty: 150,
    status: 'low',
    category: 'IT Equipment',
    unitCost: 925,
  },
  {
    id: 'invn_4',
    sku: 'FSK-COF-0087',
    name: 'FreshStock Premium Arabica Coffee',
    warehouse: 'Chicago Regional Hub',
    onHand: 900,
    reserved: 120,
    reorderPoint: 300,
    reorderQty: 500,
    status: 'healthy',
    category: 'Grocery & Pantry',
    unitCost: 14,
  },
  {
    id: 'invn_5',
    sku: 'CLR-DIS-1102',
    name: 'ClearLine Industrial Disinfectant',
    warehouse: 'Denver Fulfillment Center',
    onHand: 24,
    reserved: 10,
    reorderPoint: 50,
    reorderQty: 150,
    status: 'critical',
    category: 'Cleaning Supplies',
    unitCost: 65,
  },
  {
    id: 'invn_6',
    sku: 'VLT-LED-4432',
    name: 'VoltEdge LED Panel Light',
    warehouse: 'Charlotte East Hub',
    onHand: 980,
    reserved: 80,
    reorderPoint: 200,
    reorderQty: 300,
    status: 'overstock',
    category: 'Electrical Products',
    unitCost: 83,
  },
  {
    id: 'invn_7',
    sku: 'TNV-NET-7734',
    name: 'TechNova 24-Port Managed Switch',
    warehouse: 'Chicago Regional Hub',
    onHand: 88,
    reserved: 22,
    reorderPoint: 90,
    reorderQty: 100,
    status: 'low',
    category: 'IT Equipment',
    unitCost: 410,
  },
];

export const deliveryJobs: DeliveryJob[] = [
  {
    id: 'dlv_1',
    orderNumber: 'GO-2026-08421',
    customer: 'Cascade Financial Group',
    driver: 'Ray Thompson',
    driverPhone: '(512) 555-0148',
    vehicle: 'Box Truck · TX-8821',
    status: 'dispatched',
    progress: 65,
    eta: 'Today, 6:00 PM',
    origin: 'Austin DC',
    destination: 'Austin, TX HQ',
  },
  {
    id: 'dlv_2',
    orderNumber: 'GO-2026-08117',
    customer: 'FreshStock Order #4471',
    driver: 'Elena Vargas',
    driverPhone: '(312) 555-0199',
    vehicle: 'Sprinter Van · IL-2290',
    status: 'delivered',
    progress: 100,
    eta: 'Delivered Aug 2',
    origin: 'Chicago Hub',
    destination: 'Round Rock, TX',
  },
  {
    id: 'dlv_3',
    orderNumber: 'GO-2026-07988',
    customer: 'Cascade Financial Group',
    driver: 'Unassigned',
    driverPhone: '—',
    vehicle: 'Pending assignment',
    status: 'processing',
    progress: 10,
    eta: 'Aug 14 - Aug 16',
    origin: 'Austin DC',
    destination: 'Austin, TX HQ',
  },
  {
    id: 'dlv_4',
    orderNumber: 'GO-2026-07602',
    customer: 'Brightline Logistics',
    driver: 'Marcus Boyd',
    driverPhone: '(704) 555-0122',
    vehicle: 'Box Truck · NC-4471',
    status: 'delayed',
    progress: 40,
    eta: 'Delayed - Aug 12',
    origin: 'Charlotte Hub',
    destination: 'Charlotte, NC',
  },
  {
    id: 'dlv_5',
    orderNumber: 'GO-2026-07711',
    customer: 'Meridian Health Systems',
    driver: 'Sofia Reyes',
    driverPhone: '(720) 555-0166',
    vehicle: 'Flatbed · CO-1145',
    status: 'out-for-delivery',
    progress: 92,
    eta: 'Arriving in 20 min',
    origin: 'Denver FC',
    destination: 'Denver, CO',
  },
  {
    id: 'dlv_6',
    orderNumber: 'GO-2026-08502',
    customer: 'Cascade Financial Group',
    driver: 'Unassigned',
    driverPhone: '—',
    vehicle: 'Awaiting pickup',
    status: 'packed',
    progress: 25,
    eta: 'Aug 15 - Aug 17',
    origin: 'Austin DC',
    destination: 'Austin, TX HQ',
  },
];

export const supportTickets: SupportTicket[] = [
  {
    id: 'tkt_1',
    subject: 'Missing items in order GO-2026-07602',
    customer: 'Brightline Logistics',
    priority: 'high',
    status: 'open',
    updatedAt: '2026-08-09T14:20:00Z',
    channel: 'email',
  },
  {
    id: 'tkt_2',
    subject: 'Request for Net-30 credit increase',
    customer: 'Cascade Financial Group',
    priority: 'medium',
    status: 'pending',
    updatedAt: '2026-08-09T09:05:00Z',
    channel: 'chat',
  },
  {
    id: 'tkt_3',
    subject: 'Invoice discrepancy on INV-29988',
    customer: 'Horizon Manufacturing',
    priority: 'urgent',
    status: 'open',
    updatedAt: '2026-08-08T18:40:00Z',
    channel: 'phone',
  },
  {
    id: 'tkt_4',
    subject: 'Delivery delayed - need updated ETA',
    customer: 'Meridian Health Systems',
    priority: 'medium',
    status: 'resolved',
    updatedAt: '2026-08-07T11:00:00Z',
    channel: 'chat',
  },
  {
    id: 'tkt_5',
    subject: 'Bulk pricing question for IT equipment',
    customer: 'Apex Office Solutions',
    priority: 'low',
    status: 'resolved',
    updatedAt: '2026-08-05T16:15:00Z',
    channel: 'email',
  },
];

export const assets: Asset[] = [
  {
    id: 'ast_1',
    tag: 'GO-AST-0231',
    name: 'TechNova ProBook 14"',
    category: 'IT Equipment',
    assignedTo: 'Morgan Lee',
    location: 'Austin HQ - Floor 3',
    status: 'in-use',
    purchaseDate: '2025-03-12',
    value: 1099,
    nextMaintenance: '2026-09-01',
  },
  {
    id: 'ast_2',
    tag: 'GO-AST-0198',
    name: 'ApexRiseForm Standing Desk',
    category: 'Office Furniture',
    assignedTo: 'Priya Nair',
    location: 'Austin HQ - Floor 2',
    status: 'in-use',
    purchaseDate: '2024-11-02',
    value: 449,
    nextMaintenance: '2027-01-15',
  },
  {
    id: 'ast_3',
    tag: 'GO-AST-0305',
    name: 'VoltEdge Power Distribution Unit',
    category: 'Electrical',
    assignedTo: 'IT Infrastructure',
    location: 'Server Room B',
    status: 'maintenance',
    purchaseDate: '2023-06-20',
    value: 215,
    nextMaintenance: '2026-08-18',
  },
  {
    id: 'ast_4',
    tag: 'GO-AST-0112',
    name: 'TechNova 24-Port Switch',
    category: 'IT Equipment',
    assignedTo: 'Network Team',
    location: 'Server Room A',
    status: 'in-use',
    purchaseDate: '2023-01-08',
    value: 389,
    nextMaintenance: '2026-10-05',
  },
  {
    id: 'ast_5',
    tag: 'GO-AST-0064',
    name: 'Modular Storage Shelving',
    category: 'Office Furniture',
    assignedTo: 'Warehouse Ops',
    location: 'Round Rock Warehouse',
    status: 'in-storage',
    purchaseDate: '2022-09-30',
    value: 189,
    nextMaintenance: '2026-12-01',
  },
  {
    id: 'ast_6',
    tag: 'GO-AST-0044',
    name: 'Legacy Desktop Workstation',
    category: 'IT Equipment',
    assignedTo: 'Unassigned',
    location: 'IT Storage',
    status: 'retired',
    purchaseDate: '2020-02-14',
    value: 620,
    nextMaintenance: '—',
  },
];

export const tenders: Tender[] = [
  {
    id: 'tnd_1',
    title: 'Annual Office Furniture Refresh - HQ',
    category: 'Office Furniture',
    budget: 250000,
    deadline: '2026-09-15',
    status: 'open',
    bidCount: 6,
  },
  {
    id: 'tnd_2',
    title: 'IT Fleet Upgrade - 500 Laptops',
    category: 'IT Equipment',
    budget: 550000,
    deadline: '2026-08-25',
    status: 'evaluating',
    bidCount: 4,
  },
  {
    id: 'tnd_3',
    title: 'Facility Cleaning Services Contract',
    category: 'Cleaning Supplies',
    budget: 120000,
    deadline: '2026-08-10',
    status: 'evaluating',
    bidCount: 5,
  },
  {
    id: 'tnd_4',
    title: 'Regional Warehouse Electrical Retrofit',
    category: 'Electrical Products',
    budget: 340000,
    deadline: '2026-07-30',
    status: 'awarded',
    bidCount: 3,
  },
  {
    id: 'tnd_5',
    title: 'Corporate Breakroom Supply Contract',
    category: 'Grocery & Pantry',
    budget: 80000,
    deadline: '2026-07-01',
    status: 'closed',
    bidCount: 7,
  },
];

export const bidsByTender: Record<string, Bid[]> = {
  tnd_2: [
    {
      id: 'bid_1',
      vendorName: 'TechNova Distribution',
      amount: 512000,
      deliveryDays: 21,
      rating: 4.9,
      score: 94,
      recommended: true,
    },
    {
      id: 'bid_2',
      vendorName: 'GlobalTech Supply Co.',
      amount: 498000,
      deliveryDays: 35,
      rating: 4.4,
      score: 86,
    },
    {
      id: 'bid_3',
      vendorName: 'CompuWorld Enterprise',
      amount: 535000,
      deliveryDays: 18,
      rating: 4.6,
      score: 88,
    },
    {
      id: 'bid_4',
      vendorName: 'NextGen IT Partners',
      amount: 521000,
      deliveryDays: 28,
      rating: 4.2,
      score: 79,
    },
  ],
  tnd_3: [
    {
      id: 'bid_5',
      vendorName: 'ClearLine Janitorial Supply',
      amount: 108000,
      deliveryDays: 7,
      rating: 4.5,
      score: 91,
      recommended: true,
    },
    {
      id: 'bid_6',
      vendorName: 'SparkleClean Facilities',
      amount: 99500,
      deliveryDays: 14,
      rating: 4.1,
      score: 82,
    },
    {
      id: 'bid_7',
      vendorName: 'ProShine Commercial',
      amount: 115000,
      deliveryDays: 10,
      rating: 4.3,
      score: 85,
    },
  ],
};

export const quotesByRfq: Record<string, Bid[]> = {
  rfq_1: [
    {
      id: 'q_1',
      vendorName: 'Apex Office Solutions',
      amount: 27200,
      deliveryDays: 5,
      rating: 4.8,
      score: 95,
      recommended: true,
    },
    {
      id: 'q_2',
      vendorName: 'ErgoWorks Supply',
      amount: 25800,
      deliveryDays: 12,
      rating: 4.3,
      score: 84,
    },
    {
      id: 'q_3',
      vendorName: 'ComfortDesk Direct',
      amount: 29500,
      deliveryDays: 4,
      rating: 4.5,
      score: 87,
    },
  ],
};

export const rfqRequests: RfqRequest[] = [
  {
    id: 'rfq_1',
    title: 'Q3 Ergonomic Chairs - Regional Offices',
    requestedBy: 'Priya Nair',
    department: 'Facilities',
    category: 'Office Furniture',
    quantity: 120,
    status: 'quotes-received',
    createdAt: '2026-07-28',
    estimatedValue: 29800,
  },
  {
    id: 'rfq_2',
    title: 'Laptop Refresh - Sales Team',
    requestedBy: 'Daniel Osei',
    department: 'IT',
    category: 'IT Equipment',
    quantity: 45,
    status: 'vendor-selected',
    createdAt: '2026-07-20',
    estimatedValue: 49500,
  },
  {
    id: 'rfq_3',
    title: 'Monthly Breakroom Restock',
    requestedBy: 'Sara Kim',
    department: 'Operations',
    category: 'Grocery & Pantry',
    quantity: 300,
    status: 'po-issued',
    createdAt: '2026-08-01',
    estimatedValue: 4200,
  },
  {
    id: 'rfq_4',
    title: 'Warehouse Shelving Expansion',
    requestedBy: 'Carlos Mendes',
    department: 'Warehouse',
    category: 'Office Furniture',
    quantity: 40,
    status: 'approved',
    createdAt: '2026-07-15',
    estimatedValue: 7560,
  },
  {
    id: 'rfq_5',
    title: 'Cleaning Supplies - Q3 Bulk Order',
    requestedBy: 'Morgan Lee',
    department: 'Facilities',
    category: 'Cleaning Supplies',
    quantity: 200,
    status: 'receiving',
    createdAt: '2026-06-30',
    estimatedValue: 15600,
  },
  {
    id: 'rfq_6',
    title: 'Electrical Retrofit Materials',
    requestedBy: 'Aisha Rahman',
    department: 'Facilities',
    category: 'Electrical Products',
    quantity: 80,
    status: 'draft',
    createdAt: '2026-08-08',
    estimatedValue: 11200,
  },
  {
    id: 'rfq_7',
    title: 'Server Room Networking Gear',
    requestedBy: 'Daniel Osei',
    department: 'IT',
    category: 'IT Equipment',
    quantity: 12,
    status: 'completed',
    createdAt: '2026-06-01',
    estimatedValue: 4670,
  },
];

export const demandForecasts: DemandForecastItem[] = [
  {
    id: 'df_1',
    product: 'Apex Premium Copy Paper (Case)',
    category: 'Office Supplies',
    currentStock: 82,
    predictedDemand: 420,
    confidence: 92,
    trend: 'up',
    riskLevel: 'high',
    suggestedReorderQty: 400,
    suggestedVendor: 'Apex Office Solutions',
  },
  {
    id: 'df_2',
    product: 'TechNova ProBook 14" Laptop',
    category: 'IT Equipment',
    currentStock: 55,
    predictedDemand: 180,
    confidence: 88,
    trend: 'up',
    riskLevel: 'medium',
    suggestedReorderQty: 150,
    suggestedVendor: 'TechNova Distribution',
  },
  {
    id: 'df_3',
    product: 'ClearLine Industrial Disinfectant',
    category: 'Cleaning Supplies',
    currentStock: 24,
    predictedDemand: 140,
    confidence: 85,
    trend: 'up',
    riskLevel: 'high',
    suggestedReorderQty: 150,
    suggestedVendor: 'ClearLine Janitorial Supply',
  },
  {
    id: 'df_4',
    product: 'FreshStock Premium Arabica Coffee',
    category: 'Grocery & Pantry',
    currentStock: 900,
    predictedDemand: 620,
    confidence: 79,
    trend: 'stable',
    riskLevel: 'low',
    suggestedReorderQty: 0,
    suggestedVendor: 'FreshStock Wholesale',
  },
  {
    id: 'df_5',
    product: 'VoltEdge LED Panel Light',
    category: 'Electrical Products',
    currentStock: 980,
    predictedDemand: 310,
    confidence: 74,
    trend: 'down',
    riskLevel: 'low',
    suggestedReorderQty: 0,
    suggestedVendor: 'VoltEdge Electrical',
  },
  {
    id: 'df_6',
    product: 'ApexErgoFlex Mesh Office Chair',
    category: 'Office Furniture',
    currentStock: 340,
    predictedDemand: 260,
    confidence: 81,
    trend: 'stable',
    riskLevel: 'low',
    suggestedReorderQty: 0,
    suggestedVendor: 'Apex Office Solutions',
  },
];

export const monthlyRevenue = [
  { month: 'Feb', revenue: 182000, profit: 41000, expenses: 141000 },
  { month: 'Mar', revenue: 198000, profit: 46500, expenses: 151500 },
  { month: 'Apr', revenue: 214000, profit: 52200, expenses: 161800 },
  { month: 'May', revenue: 227000, profit: 55800, expenses: 171200 },
  { month: 'Jun', revenue: 241500, profit: 61400, expenses: 180100 },
  { month: 'Jul', revenue: 259800, profit: 68200, expenses: 191600 },
  { month: 'Aug', revenue: 271200, profit: 73500, expenses: 197700 },
];

export const categoryRevenue = [
  { label: 'IT Equipment', value: 84200 },
  { label: 'Office Furniture', value: 61300 },
  { label: 'Grocery & Pantry', value: 47800 },
  { label: 'Cleaning Supplies', value: 32100 },
  { label: 'Electrical', value: 28900 },
  { label: 'Office Supplies', value: 24600 },
];

export const vendorPerformanceScores = [
  { label: 'TechNova Distribution', value: 99.1 },
  { label: 'Apex Office Solutions', value: 98.6 },
  { label: 'FreshStock Wholesale', value: 97.2 },
  { label: 'VoltEdge Electrical', value: 97.8 },
  { label: 'ClearLine Janitorial Supply', value: 96.4 },
];
