export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  PROCUREMENT_MANAGER: 'PROCUREMENT_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  SALES_MANAGER: 'SALES_MANAGER',
  MANAGER: 'MANAGER',
  USER: 'USER',
  VIEWER: 'VIEWER',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  USERS_DELETE: 'users:delete',
  SETTINGS_READ: 'settings:read',
  SETTINGS_WRITE: 'settings:write',
  DASHBOARD_READ: 'dashboard:read',
  PROFILE_READ: 'profile:read',
  PROFILE_WRITE: 'profile:write',
  AUDIT_READ: 'audit:read',
  ADMIN_ACCESS: 'admin:access',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ADMIN_ACCESS,
  ],
  // GoOrder Admin Dashboard department roles — each manages their own module
  // (finance/credit/invoicing, procurement/vendors, inventory, or sales/orders)
  // but shares the same Admin Panel entry point as ADMIN.
  FINANCE_MANAGER: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.ADMIN_ACCESS,
  ],
  PROCUREMENT_MANAGER: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.ADMIN_ACCESS,
  ],
  INVENTORY_MANAGER: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.ADMIN_ACCESS,
  ],
  SALES_MANAGER: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.ADMIN_ACCESS,
  ],
  MANAGER: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_WRITE,
  ],
  USER: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_WRITE,
    PERMISSIONS.SETTINGS_READ,
  ],
  VIEWER: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.PROFILE_READ, PERMISSIONS.SETTINGS_READ],
};

export const ROLE_HIERARCHY: Record<Role, number> = {
  SUPER_ADMIN: 100,
  ADMIN: 80,
  FINANCE_MANAGER: 70,
  PROCUREMENT_MANAGER: 70,
  INVENTORY_MANAGER: 70,
  SALES_MANAGER: 70,
  MANAGER: 60,
  USER: 40,
  VIEWER: 20,
};
